### ISSUE TITLE
Slight improvement to `rails routes` command

### ISSUE THREAD

**Issue by TheDauthi** [okeeffed/rails-gen-openapi#1]
Not really an issue, but I didn't see a way to comment on your blog entry (I was also going to answer a couple of your questions).

I'd use this to save the routes instead:

`bin/rails routes | ruby -pe 'sub(/.+?(?=GET|DELETE|POST|PUT|PATCH)/, "")' > routes.txt`

This skips the next step, where the user needs to do a regex replace in their editor (and then wonders why it doesn't work since some editors don't support regex lookahead, grumble grumble).

You may even want to extend that further to 
`bin/rails routes | ruby -pe 'sub(/.+?(?=GET|DELETE|POST|PUT|PATCH)/, "")' | ruby -pe 'sub(/\(\.:format\)/,"")'  > routes.txt`

to eliminate the (.:format) that exists when you can render multiple formats based on extensions.

**Comment by okeeffed** [comment]
Awesome shout, thanks for that one!
